/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseFunctionRouteImport } from './routes/use-function'
import { Route as TransitionRouteImport } from './routes/transition'
import { Route as DeferredValueRouteImport } from './routes/deferred-value'

const UseFunctionRoute = UseFunctionRouteImport.update({
  id: '/use-function',
  path: '/use-function',
  getParentRoute: () => rootRouteImport,
} as any)
const TransitionRoute = TransitionRouteImport.update({
  id: '/transition',
  path: '/transition',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredValueRoute = DeferredValueRouteImport.update({
  id: '/deferred-value',
  path: '/deferred-value',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/deferred-value': typeof DeferredValueRoute
  '/transition': typeof TransitionRoute
  '/use-function': typeof UseFunctionRoute
}
export interface FileRoutesByTo {
  '/deferred-value': typeof DeferredValueRoute
  '/transition': typeof TransitionRoute
  '/use-function': typeof UseFunctionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/deferred-value': typeof DeferredValueRoute
  '/transition': typeof TransitionRoute
  '/use-function': typeof UseFunctionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/deferred-value' | '/transition' | '/use-function'
  fileRoutesByTo: FileRoutesByTo
  to: '/deferred-value' | '/transition' | '/use-function'
  id: '__root__' | '/deferred-value' | '/transition' | '/use-function'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DeferredValueRoute: typeof DeferredValueRoute
  TransitionRoute: typeof TransitionRoute
  UseFunctionRoute: typeof UseFunctionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-function': {
      id: '/use-function'
      path: '/use-function'
      fullPath: '/use-function'
      preLoaderRoute: typeof UseFunctionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transition': {
      id: '/transition'
      path: '/transition'
      fullPath: '/transition'
      preLoaderRoute: typeof TransitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred-value': {
      id: '/deferred-value'
      path: '/deferred-value'
      fullPath: '/deferred-value'
      preLoaderRoute: typeof DeferredValueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DeferredValueRoute: DeferredValueRoute,
  TransitionRoute: TransitionRoute,
  UseFunctionRoute: UseFunctionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
